// lib/imoveis-data.ts

export type ImovelCompleto = {
  id: string
  title: string
  price: string
  location: string
  type: "venda" | "aluguel" | "comercial"
  coverImage: string
  bedrooms?: number
  bathrooms: number
  parking: number
  area: string
  description: string
  videos?: string[]
  images: string[]
  amenities: string[]
  backUrl: string
  backLabel: string
}

export const todosImoveis: ImovelCompleto[] = [
  // --- VENDA ---
  {
    id: "ap-viver-bem-indianopolis-908",
    title: "Apartamento no Viver Bem Indianópolis",
    price: "Consulte o valor",
    location: "Indianópolis, Caruaru - PE",
    type: "venda",
    coverImage: "/imoveis/apartamentos-para-venda/edificio-viver-bem-indianopolis/1.jpeg",
    bedrooms: 3,
    bathrooms: 2,
    parking: 1,
    area: "63,25m²",
    description: `Excelente apartamento de 63,25 m², localizado na Torre 1 – apartamento 908, com uma planta moderna, funcional e bem distribuída.

O imóvel conta com 3 quartos, sendo 1 suíte, sala para 2 ambientes, varanda, banheiro social e cozinha integrada à área de serviço, proporcionando praticidade e conforto para o dia a dia.

Estrutura completa de lazer, bem-estar e conveniência:
• Piscina com raia semiolímpica e piscina infantil
• Espaço churrasco e Espaço Gourmet
• Salão de festas
• Academia equipada
• Sala multifuncional
• Coworking
• Espaço Box e bicicletário
• Ponto de carregamento para veículo elétrico`,
    videos: ["/imoveis/apartamentos-para-venda/edificio-viver-bem-indianopolis/1.mp4"],
    images: Array.from({ length: 38 }, (_, i) => `/imoveis/apartamentos-para-venda/edificio-viver-bem-indianopolis/${i + 1}.jpeg`),
    amenities: [
      "1 Suíte",
      "Varanda",
      "Piscina com Raia Semiolímpica",
      "Piscina Infantil",
      "Academia Equipada",
      "Espaço Gourmet e Churrasqueira",
      "Coworking",
      "Ponto para Veículo Elétrico",
      "Bicicletário",
      "Salão de Festas",
    ],
    backUrl: "/empreendimentos/imoveis-para-venda",
    backLabel: "Voltar para Imóveis para Venda",
  },
  {
    id: "casa-monte-castelo-gravata",
    title: "Mansão de Alto Padrão no Condomínio Monte Castelo",
    price: "R$ 2.400.000",
    location: "Condomínio Monte Castelo, Gravatá - PE",
    type: "venda",
    coverImage: "/imoveis/casas-para-venda/casa-monte-castelo-gravata/5.jpeg",
    bedrooms: 6,
    bathrooms: 7,
    parking: 6,
    area: "1.000m² terreno (com lote anexo)",
    description: `Exclusiva mansão de alto padrão no prestigiado Condomínio Monte Castelo em Gravatá - PE. Imóvel e lote totalmente escriturados. Projeto de arquitetura moderna integrando madeira nobre, vidro e concreto aparente.`,
    videos: ["/imoveis/casas-para-venda/casa-monte-castelo-gravata/1.mp4"],
    images: [
      "/imoveis/casas-para-venda/casa-monte-castelo-gravata/5.jpeg",
      ...Array.from({ length: 18 }, (_, i) => `/imoveis/casas-para-venda/casa-monte-castelo-gravata/${i + 2}.jpeg`),
    ],
    amenities: ["6 Suítes Privativas", "Lote Anexo 20x50m Incluso", "Varanda Panorâmica", "Espaço Gourmet", "Garagem para 6 Veículos", "Portaria 24h"],
    backUrl: "/empreendimentos/imoveis-para-venda",
    backLabel: "Voltar para Imóveis para Venda",
  },
  {
    id: "casa-moderna-com-quintal",
    title: "Casa Moderna com Quintal e Excelente Padrão",
    price: "Consulte o valor",
    location: "Caruaru - PE",
    type: "venda",
    coverImage: "/imoveis/casas-para-venda/casa-moderna-com-quintal/1.jpeg",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    area: "56m²",
    description: `Excelente oportunidade de casa à venda com ótimo padrão de acabamento e quintal amplo nos fundos de 5x7m com potencial de expansão.`,
    images: Array.from({ length: 10 }, (_, i) => `/imoveis/casas-para-venda/casa-moderna-com-quintal/${i + 1}.jpeg`),
    amenities: ["1 Suíte", "Cozinha Planejada", "Quintal Amplo (5x7m)", "Garagem Privativa", "Projeto Luminotécnico"],
    backUrl: "/empreendimentos/imoveis-para-venda",
    backLabel: "Voltar para Imóveis para Venda",
  },
  {
    id: "casa-the-house-club-caruaru",
    title: "Casa em Condomínio Fechado no The House Club",
    price: "R$ 870.000",
    location: "Luiz Gonzaga, Caruaru - PE",
    type: "venda",
    coverImage: "/imoveis/casas-para-venda/casa-the-house-club/1.jpeg",
    bedrooms: 3,
    bathrooms: 4,
    parking: 2,
    area: "123m²",
    description: `Excelente casa em condomínio fechado com 3 suítes, espaço gourmet, preparação para jacuzzi e área de lazer completa. Aceita financiamento.`,
    images: Array.from({ length: 18 }, (_, i) => `/imoveis/casas-para-venda/casa-the-house-club/${i + 1}.jpeg`),
    amenities: ["3 Suítes", "Espaço Gourmet", "Preparação para Jacuzzi", "Piscina e Academia", "Portaria 24h"],
    backUrl: "/empreendimentos/imoveis-para-venda",
    backLabel: "Voltar para Imóveis para Venda",
  },
  {
    id: "ap-vog-ville-norte",
    title: "Apartamento Pronto para Morar no Vog Ville Norte",
    price: "R$ 290.000",
    location: "Caruaru - PE",
    type: "venda",
    coverImage: "/imoveis/apartamentos-para-venda/edificio-vog-ville-norte/3.jpeg",
    bedrooms: 2,
    bathrooms: 2,
    parking: 1,
    area: "52m²",
    description: `Apartamento completo, pronto para morar, com móveis planejados, ar-condicionado e lazer com piscina e academia.`,
    videos: [
      "/imoveis/apartamentos-para-venda/edificio-vog-ville-norte/1.mp4",
      "/imoveis/apartamentos-para-venda/edificio-vog-ville-norte/2.mp4",
    ],
    images: Array.from({ length: 20 }, (_, i) => `/imoveis/apartamentos-para-venda/edificio-vog-ville-norte/${i + 3}.jpeg`),
    amenities: ["1 Suíte", "Ar-condicionado", "Móveis Planejados", "Piscina Adulto e Infantil", "Academia Equipada"],
    backUrl: "/empreendimentos/imoveis-para-venda",
    backLabel: "Voltar para Imóveis para Venda",
  },
  {
    id: "ap-edificio-santa-maria-boa-viagem",
    title: "Apartamento de Alto Padrão no Edifício Santa Maria",
    price: "R$ 2.200.000",
    location: "Boa Viagem, Recife - PE",
    type: "venda",
    coverImage: "/imoveis/apartamentos-para-venda/edificio-santa-maria/1.jpeg",
    bedrooms: 4,
    bathrooms: 6,
    parking: 3,
    area: "180m²",
    description: `Apartamento amplo de alto padrão com vista definitiva para o mar em Boa Viagem, 4 suítes, 3 vagas e lazer completo.`,
    images: Array.from({ length: 29 }, (_, i) => `/imoveis/apartamentos-para-venda/edificio-santa-maria/${i + 1}.jpeg`),
    amenities: ["4 Suítes", "Vista para o Mar", "3 Vagas de Garagem", "Estação de Carro Elétrico", "Piscina e Sauna"],
    backUrl: "/empreendimentos/imoveis-para-venda",
    backLabel: "Voltar para Imóveis para Venda",
  },

  // --- LOCAÇÃO ---
  {
    id: "ap-condominio-mr-rotterdam",
    title: "Apartamento Mobiliado no Condomínio Mr. Rotterdam",
    price: "R$ 2.400 / mês (Incluso Condomínio e IPTU)",
    location: "Universitário, Caruaru - PE",
    type: "aluguel",
    coverImage: "/imoveis/apartamentos-para-alugar/edificio-mr-rotterdam/2.jpeg",
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    area: "38m²",
    description: `Apartamento mobiliado e completo no Condomínio Mr. Rotterdam na Av. Amazonas no Bairro Universitário. Vista Sul, 4º andar, piscina e academia.`,
    images: [
      "/imoveis/apartamentos-para-alugar/edificio-mr-rotterdam/2.jpeg",
      "/imoveis/apartamentos-para-alugar/edificio-mr-rotterdam/1.jpeg",
      ...Array.from({ length: 13 }, (_, i) => `/imoveis/apartamentos-para-alugar/edificio-mr-rotterdam/${i + 3}.jpeg`),
    ],
    amenities: ["100% Mobiliado", "4º Andar (Vista Sul)", "Piscina Adulto e Infantil", "Academia", "Portaria 24h"],
    backUrl: "/empreendimentos/imoveis-para-alugar",
    backLabel: "Voltar para Imóveis para Alugar",
  },
  {
    id: "ap-mobiliado-mauricio-de-nassau",
    title: "Apartamento Mobiliado no Maurício de Nassau",
    price: "R$ 1.700 / mês (Incluso Taxas)",
    location: "Maurício de Nassau, Caruaru - PE",
    type: "aluguel",
    coverImage: "/imoveis/apartamentos-para-alugar/apartamento-mobiliado-mauricio-de-nassau/1.jpeg",
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    area: "35m²",
    description: `Apartamento mobiliado no bairro Maurício de Nassau, próximo ao polo médico e jurídico. Taxas inclusas.`,
    images: Array.from({ length: 9 }, (_, i) => `/imoveis/apartamentos-para-alugar/apartamento-mobiliado-mauricio-de-nassau/${i + 1}.jpeg`),
    amenities: ["Mobiliado", "Ar-condicionado", "Próximo ao Polo Médico", "Taxas Inclusas"],
    backUrl: "/empreendimentos/imoveis-para-alugar",
    backLabel: "Voltar para Imóveis para Alugar",
  },
  {
    id: "ap-edificio-tereza-rodrigues",
    title: "Apartamento no Edifício Tereza Rodrigues",
    price: "R$ 4.000 / mês (Incluso Condomínio)",
    location: "Boa Viagem, Recife - PE",
    type: "aluguel",
    coverImage: "/imoveis/apartamentos-para-alugar/edificio-tereza-rodrigues/1.jpeg",
    bedrooms: 2,
    bathrooms: 3,
    parking: 1,
    area: "64m²",
    description: `Excelente oportunidade no Edifício Tereza Rodrigues em Boa Viagem. Andar alto com vista aberta e 1 suíte.`,
    images: Array.from({ length: 34 }, (_, i) => `/imoveis/apartamentos-para-alugar/edificio-tereza-rodrigues/${i + 1}.jpeg`),
    amenities: ["Andar Alto", "Varanda", "1 Suíte", "Dependência Completa", "Condomínio Incluso"],
    backUrl: "/empreendimentos/imoveis-para-alugar",
    backLabel: "Voltar para Imóveis para Alugar",
  },
  {
    id: "ap-edificio-jardim-dos-alecrins",
    title: "Apartamento Mobiliado no Edifício Jardim dos Alecrins",
    price: "R$ 2.800 / mês (Incluso Taxas)",
    location: "Universitário, Caruaru - PE",
    type: "aluguel",
    coverImage: "/imoveis/apartamentos-para-alugar/edificio-jardim-dos-alecrins/1.jpeg",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    area: "54m²",
    description: `Apartamento nascente e mobiliado no Edifício Jardim dos Alecrins, próximo à ASCES no Bairro Universitário.`,
    images: Array.from({ length: 33 }, (_, i) => `/imoveis/apartamentos-para-alugar/edificio-jardim-dos-alecrins/${i + 1}.jpeg`),
    amenities: ["Totalmente Mobiliado", "Nascente", "Piscina e Salão de Festas", "Portaria 24h", "Taxas Inclusas"],
    backUrl: "/empreendimentos/imoveis-para-alugar",
    backLabel: "Voltar para Imóveis para Alugar",
  },
  {
    id: "ap-studio-alto-padrao-shopping",
    title: "Apartamento de Alto Padrão - Pronto para Morar",
    price: "R$ 4.000 / mês",
    location: "Maurício de Nassau, Caruaru - PE",
    type: "aluguel",
    coverImage: "/imoveis/apartamentos-para-alugar/apartamento-alto-padrao-pronto-morar/1.jpeg",
    bedrooms: 1,
    bathrooms: 1,
    parking: 1,
    area: "38m²",
    description: `Apartamento alto padrão decorado e mobiliado em complexo comercial no Maurício de Nassau.`,
    videos: ["/imoveis/apartamentos-para-alugar/apartamento-alto-padrao-pronto-morar/19.mp4"],
    images: Array.from({ length: 29 }, (_, i) => `/imoveis/apartamentos-para-alugar/apartamento-alto-padrao-pronto-morar/${i + 1}.jpeg`),
    amenities: ["Mobiliado e Decorado", "Complexo com Shopping", "Academia e Coworking", "Portaria 24h"],
    backUrl: "/empreendimentos/imoveis-para-alugar",
    backLabel: "Voltar para Imóveis para Alugar",
  },
  {
    id: "ap-edificio-joao-soares",
    title: "Apartamento de Alto Padrão no Edifício João Soares",
    price: "R$ 4.200 / mês (Incluso Taxas)",
    location: "Maurício de Nassau, Caruaru - PE",
    type: "aluguel",
    coverImage: "/imoveis/apartamentos-para-alugar/edificio-joao-soares/1.jpeg",
    bedrooms: 2,
    bathrooms: 3,
    parking: 2,
    area: "80m²",
    description: `Apartamento com móveis Finger de alto padrão, andar alto, 2 suítes e 2 vagas de garagem cobertas no Maurício de Nassau.`,
    images: Array.from({ length: 13 }, (_, i) => `/imoveis/apartamentos-para-alugar/edificio-joao-soares/${i + 1}.jpeg`),
    amenities: ["Móveis Planejados Finger", "2 Suítes", "2 Vagas Cobertas", "Portaria 24h", "Taxas Inclusas"],
    backUrl: "/empreendimentos/imoveis-para-alugar",
    backLabel: "Voltar para Imóveis para Alugar",
  },
  {
    id: "ap-caminho-das-aroeiras",
    title: "Apartamento Condomínio Caminho das Aroeiras",
    price: "Consulte o valor",
    location: "Indianópolis, Caruaru - PE",
    type: "aluguel",
    coverImage: "/imoveis/apartamentos-para-alugar/caminho-das-aroeiras/7.jpeg",
    bedrooms: 2,
    bathrooms: 1,
    parking: 1,
    area: "52m²",
    description: `Apartamento ventilado ao lado do Caruaru Shopping com lazer completo e segurança 24 horas.`,
    images: Array.from({ length: 10 }, (_, i) => `/imoveis/apartamentos-para-alugar/caminho-das-aroeiras/${i + 1}.jpeg`),
    amenities: ["Próximo ao Caruaru Shopping", "Piscina e Salão de Festas", "Portaria 24h", "Vaga Privativa"],
    backUrl: "/empreendimentos/imoveis-para-alugar",
    backLabel: "Voltar para Imóveis para Alugar",
  },

  // --- COMERCIAL ---
  {
    id: "ponto-comercial-agamenon-magalhaes",
    title: "Ponto Comercial na Avenida Agamenon Magalhães",
    price: "R$ 4.500 / mês",
    location: "Av. Agamenon Magalhães, Caruaru - PE",
    type: "comercial",
    coverImage: "/imoveis/pontos-comerciais/ponto-comercial-agamenon-magalhaes/1.jpeg",
    bathrooms: 1,
    parking: 0,
    area: "25m² (5m x 5m)",
    description: `Ponto comercial na principal avenida de Caruaru: Av. Agamenon Magalhães. Alto fluxo de pedestres e carros.`,
    images: Array.from({ length: 4 }, (_, i) => `/imoveis/pontos-comerciais/ponto-comercial-agamenon-magalhaes/${i + 1}.jpeg`),
    amenities: ["Avenida Principal", "Excelente Visibilidade", "1 Banheiro", "Alto Fluxo"],
    backUrl: "/empreendimentos/pontos-comerciais",
    backLabel: "Voltar para Pontos Comerciais",
  },
]